### ISSUE TITLE
Scala 2.11

### ISSUE THREAD

**Issue by apfeffer** [p2t2/figaro#182]
I looks like Figaro doesn't work in Scala 2.11. I've been getting comments from readers of the book. Can we look into making it work for our next release? In addition to making it easier for readers of the book, summer school will run more smoothly if people can use the latest version of Scala.

**Comment by dotnetCarpenter** [comment]
After following the instructions in the book *Practical Probability Programming* appendix A.3, I get the following when running the `package` command:

```
[error] File name too long
[warn] 6 warnings found
[error] one error found
[error] (Figaro/compile:compileIncremental) Compilation failed
[error] Total time: 574 s, completed Sep 23, 2016 3:46:24 PM
```
The `compile` command automatically downloads scala **2.11.7**.

```
> compile
[info] Updating {file:/home/dotnet/projects/opensource/figaro/}Figaro...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.jar ...
[info] 	[SUCCESSFUL ] org.scala-lang#scala-library;2.11.7!scala-library.jar (41723ms)
```

I'm trying to compile the *master* branch.
